
import streamlit as st
import pickle
import pandas as pd
import numpy as np

# --- Load the processed DataFrame and similarity matrix ---
# Ensure 'movie_data.pkl' and 'similarity_matrix.pkl' are in the same directory
# as this Streamlit app, or provide the correct path.

try:
    with open('movie_data.pkl', 'rb') as f:
        new_df = pickle.load(f)
    with open('similarity_matrix.pkl', 'rb') as f:
        similarity = pickle.load(f)

    # Convert similarity from list to numpy array if it was stored as list of lists
    if isinstance(similarity, list):
        similarity = np.array(similarity)

    st.success("Recommendation data loaded successfully!")
except FileNotFoundError:
    st.error("Error: 'movie_data.pkl' or 'similarity_matrix.pkl' not found.")
    st.warning("Please ensure these files are generated by running the notebook cells before starting the Streamlit app.")
    new_df = pd.DataFrame({'title': ['Data Not Loaded']}) # Fallback for UI
    similarity = None

# --- Recommendation Logic ---
def recommend(movie_title):
    if new_df.empty or similarity is None or (isinstance(similarity, np.ndarray) and similarity.size == 0):
        return ["Recommendation system not initialized. Data files might be missing or empty."]

    try:
        # Ensure title column exists and case-insensitive comparison
        if 'title' not in new_df.columns:
            return ["Movie titles column not found in data."]
        
        # Get the index of the movie that matches the title
        movie_index = new_df[new_df['title'].str.lower() == movie_title.lower()].index[0]
    except IndexError:
        return ["Movie not found in the database. Please check the title."]

    # Get similarity scores for the given movie
    distances = similarity[movie_index]

    # Sort movies by similarity distance (descending) and get top 5 (excluding itself)
    # We use enumerate to keep track of the original indices
    # Sort by the distance (second element of the tuple) in reverse order
    movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])

    recommended_movies = []
    for i in movies_list[1:6]: # Start from index 1 to exclude the input movie itself
        recommended_movies.append(new_df.iloc[i[0]].title)
    return recommended_movies

# --- Streamlit UI ---
st.title('Movie Recommender System')
st.markdown("### Get movie recommendations based on your selection!")

movie_list = new_df['title'].tolist()
selected_movie = st.selectbox(
    "Type or select a movie from the dropdown",
    movie_list
)

if st.button('Show Recommendation'):
    if selected_movie:
        recommendations = recommend(selected_movie)
        if recommendations:
            st.write(f"Recommendations for **{selected_movie}**:")
            for i, movie in enumerate(recommendations):
                st.write(f"{i+1}. {movie}")
        else:
            st.write("No recommendations found for this movie.")
    else:
        st.warning("Please select a movie.")

st.markdown("---")
st.info("To run this app locally: `streamlit run streamlit_app.py`")
